In [2]:
import pandas as pd
import os
import os
import ssl
import urllib.request
import zipfile
from pathlib import Path

import certifi
import pandas as pd
from aieng.agent_evals.async_client_manager import AsyncClientManager

In [2]:
print("hello world")

hello world

In [ ]:
import kagglehub

kagglehub.login()

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("namigabbasov/consumer-complaint-dataset")

print("Path to dataset files:", path)

Path to dataset files: /home/coder/.cache/kagglehub/datasets/namigabbasov/consumer-complaint-dataset/versions/1

In [13]:
client_manager = AsyncClientManager.get_instance()
assert client_manager.configs.report_generation_db.database, (
    "[ERROR] The database path is not set! Please configure the REPORT_GENERATION_DB__DATABASE environment variable."
)

print("All environment variables have been set.")

All environment variables have been set.

In [14]:
full_file_path = os.path.join('/home/coder/.cache/kagglehub/datasets/namigabbasov/consumer-complaint-dataset/versions/1', "complaints.csv")
df = pd.read_csv(full_file_path)

In [15]:
df.head()

,id,product_type,narrative,product_type_specific,date_recieved,sub_product,issue,sub_issue,company,state,timely_response
0,234,Credit Reporting,Dear Possible Financial Inc you guyss aree rep...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Incorrect information on your report,Account information incorrect,Possible Financial Inc,MI,Yes
1,240,Debt Collection,"XXXX XXXX XXXX ( debt collector ), sent my boy...",Debt collection,2024-07-27,I do not know,Threatened to contact someone or share informa...,Talked to a third-party about your debt,BlueChip Financial,TX,Yes
2,257,Credit Reporting,I been receiving alerts my information was fou...,Credit reporting or other personal consumer re...,2024-07-23,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,FC HoldCo LLC,SC,Yes
3,271,Credit Reporting,Subject : Dispute of Inaccurate Information on...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Improper use of your report,Reporting company used your report improperly,CORELOGIC INC,GA,Yes
4,276,Loans,They allowed me to use the account for about a...,"Payday loan, title loan, personal loan, or adv...",2024-07-26,Payday loan,Received a loan you didn't apply for,NaN,MoneyLion Inc.,PA,Yes

In [16]:
new_names = {'Unnamed: 0': 'id', 'product_5': 'product_type', 'Product': 'product_type_specific', 'date_recieved': 'date_received', 'Sub-product': 'sub_product', 'Issue': 'issue', 'Sub-issue': 'sub_issue', 'Company': 'company', 'State': 'state', 'Timely response?': 'timely_response'}
df = df.rename(columns=new_names)
# df['date_recieved'] = pd.to_datetime(df['date_recieved'])

In [17]:
df.head()

,id,product_type,narrative,product_type_specific,date_received,sub_product,issue,sub_issue,company,state,timely_response
0,234,Credit Reporting,Dear Possible Financial Inc you guyss aree rep...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Incorrect information on your report,Account information incorrect,Possible Financial Inc,MI,Yes
1,240,Debt Collection,"XXXX XXXX XXXX ( debt collector ), sent my boy...",Debt collection,2024-07-27,I do not know,Threatened to contact someone or share informa...,Talked to a third-party about your debt,BlueChip Financial,TX,Yes
2,257,Credit Reporting,I been receiving alerts my information was fou...,Credit reporting or other personal consumer re...,2024-07-23,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,FC HoldCo LLC,SC,Yes
3,271,Credit Reporting,Subject : Dispute of Inaccurate Information on...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Improper use of your report,Reporting company used your report improperly,CORELOGIC INC,GA,Yes
4,276,Loans,They allowed me to use the account for about a...,"Payday loan, title loan, personal loan, or adv...",2024-07-26,Payday loan,Received a loan you didn't apply for,NaN,MoneyLion Inc.,PA,Yes

In [18]:
df.dtypes

id                        int64
product_type             object
narrative                object
product_type_specific    object
date_received            object
sub_product              object
issue                    object
sub_issue                object
company                  object
state                    object
timely_response          object
dtype: object

In [20]:
df.iloc[:10000]

,id,product_type,narrative,product_type_specific,date_received,sub_product,issue,sub_issue,company,state,timely_response
0,234,Credit Reporting,Dear Possible Financial Inc you guyss aree rep...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Incorrect information on your report,Account information incorrect,Possible Financial Inc,MI,Yes
1,240,Debt Collection,"XXXX XXXX XXXX ( debt collector ), sent my boy...",Debt collection,2024-07-27,I do not know,Threatened to contact someone or share informa...,Talked to a third-party about your debt,BlueChip Financial,TX,Yes
2,257,Credit Reporting,I been receiving alerts my information was fou...,Credit reporting or other personal consumer re...,2024-07-23,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,FC HoldCo LLC,SC,Yes
3,271,Credit Reporting,Subject : Dispute of Inaccurate Information on...,Credit reporting or other personal consumer re...,2024-07-27,Credit reporting,Improper use of your report,Reporting company used your report improperly,CORELOGIC INC,GA,Yes
4,276,Loans,They allowed me to use the account for about a...,"Payday loan, title loan, personal loan, or adv...",2024-07-26,Payday loan,Received a loan you didn't apply for,NaN,MoneyLion Inc.,PA,Yes
...,...,...,...,...,...,...,...,...,...,...,...
9995,148616,Credit Reporting,The Fair Credit Reporting Act ( 15 U.S. Code 1...,Credit reporting or other personal consumer re...,2024-06-25,Credit reporting,Incorrect information on your report,Information belongs to someone else,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,Yes
9996,148619,Credit Reporting,I do not recognize the account listed on my cr...,Credit reporting or other personal consumer re...,2024-06-25,Credit reporting,Incorrect information on your report,Information belongs to someone else,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",IL,Yes
9997,148621,Credit Reporting,Could you please remove the inquiries reported...,Credit reporting or other personal consumer re...,2024-06-25,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",GA,Yes
9998,148622,Credit Reporting,I am writing to dispute an unauthorized inquir...,Credit reporting or other personal consumer re...,2024-06-25,Credit reporting,Incorrect information on your report,Information belongs to someone else,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PA,Yes
9999,148623,Credit Reporting,My account with XXXX was never late! I have ha...,Credit reporting or other personal consumer re...,2024-06-25,Credit reporting,Incorrect information on your report,Account status incorrect,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",NY,Yes

In [26]:
df.to_csv(new_path, index=False)

In [4]:
os.chdir(Path('/home/coder/eval-agents'))

In [8]:
new_path = os.path.join('/home/coder/eval-agents/td_team_3/', "cleaned_complaints.csv")

In [14]:
import td_team_3.import_complaints_data

In [15]:
td_team_3.import_complaints_data.import_complaints_data(new_path)

2026-03-25 18:30:40,240 INFO td_team_3.import_complaints_data: Creating tables according to the OnlineRetail.ddl file
2026-03-25 18:30:40,242 INFO td_team_3.import_complaints_data: Importing dataset from /home/coder/eval-agents/td_team_3/cleaned_complaints.csv to database at implementations/report_generation/data/OnlineRetail.db

OperationalError: database or disk is full

In [16]:
import sqlite3

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [17]:
sqlite3.connect('/home/coder/eval-agents/implementations/report_generation/data/Complaints.db')

In [42]:
import sqlite3
con = sqlite3.connect("/home/coder/eval-agents/implementations/report_generation/data/OnlineRetail.db")

In [28]:
cur = con.cursor()

In [39]:

cur.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()

[('sales',), ('complaints',)]

In [41]:

cur.execute("SELECT COUNT(*) FROM complaints").fetchall()

[(2023066,)]

In [38]:
res = cur.execute("SELECT * FROM sqlite_master")
res.fetchone()

('table',
 'sales',
 'sales',
 2,
 'CREATE TABLE "sales" (\n        "InvoiceNo" INTEGER,\n        "StockCode" TEXT,\n        "Description" TEXT,\n        "Quantity" INTEGER,\n        "InvoiceDate" TEXT,\n        "UnitPrice" REAL,\n        "CustomerID" INTEGER,\n        "Country" TEXT\n)')